export const products = [
  {
    id: 1,
    name: "Quantum Widget",
    ratings: "⭐⭐⭐⭐⭐",
    author: "Elara Vance",
  },
  { id: 2, name: "Gizmo Flux", ratings: "⭐⭐⭐", author: "Jasper Holt" },
  {
    id: 3,
    name: "Nebula Notebook",
    ratings: "⭐⭐⭐⭐",
    author: "Serena Quill",
  },
  { id: 4, name: "Pixel Lantern", ratings: "⭐⭐", author: "Finn Carver" },
  {
    id: 5,
    name: "Echo Sphere",
    ratings: "⭐⭐⭐⭐⭐",
    author: "Lila Sterling",
  },
  { id: 6, name: "Chrono Pen", ratings: "⭐⭐⭐", author: "Miles Thorn" },
  { id: 7, name: "Aether Board", ratings: "⭐⭐⭐⭐", author: "Nora Blake" },
  { id: 8, name: "Vortex Mug", ratings: "⭐", author: "Caleb Wren" },
  { id: 9, name: "Starlight Key", ratings: "⭐⭐⭐⭐⭐", author: "Iris Faye" },
  { id: 10, name: "Glint Compass", ratings: "⭐⭐⭐", author: "Ezra Pine" },
  { id: 11, name: "Prism Watch", ratings: "⭐⭐⭐⭐", author: "Violet Sage" },
  { id: 12, name: "Zephyr Drone", ratings: "⭐⭐", author: "Gideon Frost" },
  {
    id: 13,
    name: "Lumen Speaker",
    ratings: "⭐⭐⭐⭐⭐",
    author: "Clara Dune",
  },
  { id: 14, name: "Orbit Lamp", ratings: "⭐⭐⭐", author: "Theo Marsh" },
  { id: 15, name: "Nova Charger", ratings: "⭐⭐⭐⭐", author: "Selene Crow" },
  { id: 16, name: "Astral Backpack", ratings: "⭐⭐", author: "Rory Flint" },
  {
    id: 17,
    name: "Pulsar Headphones",
    ratings: "⭐⭐⭐⭐⭐",
    author: "Amara Leaf",
  },
  { id: 18, name: "Spark Tablet", ratings: "⭐⭐⭐", author: "Silas Oak" },
  {
    id: 19,
    name: "Horizon Camera",
    ratings: "⭐⭐⭐⭐",
    author: "Freya Stone",
  },
  { id: 20, name: "Crimson Journal", ratings: "⭐", author: "Leif Arrow" },
  { id: 21, name: "Solar Mouse", ratings: "⭐⭐⭐⭐⭐", author: "Mira Vale" },
  { id: 22, name: "Tidal Earbuds", ratings: "⭐⭐⭐", author: "Declan Storm" },
  {
    id: 23,
    name: "Ember Projector",
    ratings: "⭐⭐⭐⭐",
    author: "Lyra Breeze",
  },
  { id: 24, name: "Frost Scanner", ratings: "⭐⭐", author: "Kael Ember" },
  {
    id: 25,
    name: "Celestine Clock",
    ratings: "⭐⭐⭐⭐⭐",
    author: "Tessa Rune",
  },
  {
    id: 26,
    name: "Radiant Keyboard",
    ratings: "⭐⭐⭐",
    author: "Orion Shade",
  },
  { id: 27, name: "Sable Router", ratings: "⭐⭐⭐⭐", author: "Elowen Mist" },
  { id: 28, name: "Dawn Monitor", ratings: "⭐⭐", author: "Bram Clover" },
  {
    id: 29,
    name: "Twilight Hub",
    ratings: "⭐⭐⭐⭐⭐",
    author: "Sienna Glade",
  },
  { id: 30, name: "Comet Tripod", ratings: "⭐⭐⭐", author: "Zane Quill" },
  { id: 31, name: "Lunar Mat", ratings: "⭐⭐⭐⭐", author: "Aurora Flint" },
  { id: 32, name: "Stellar Drive", ratings: "⭐", author: "Caspian Tide" },
  {
    id: 33,
    name: "Meteor Stylus",
    ratings: "⭐⭐⭐⭐⭐",
    author: "Livia Thorn",
  },
  { id: 34, name: "Cosmo Frame", ratings: "⭐⭐⭐", author: "Felix Dawn" },
  { id: 35, name: "Eclipse Reader", ratings: "⭐⭐⭐⭐", author: "Selma Ray" },
  { id: 36, name: "Nimbus Planner", ratings: "⭐⭐", author: "Hugo Slate" },
  {
    id: 37,
    name: "Flare Console",
    ratings: "⭐⭐⭐⭐⭐",
    author: "Esme Cloud",
  },
  { id: 38, name: "Cobalt Cable", ratings: "⭐⭐⭐", author: "Rowan Haze" },
  { id: 39, name: "Opal Tracker", ratings: "⭐⭐⭐⭐", author: "Lena Spark" },
  { id: 40, name: "Quartz Adapter", ratings: "⭐", author: "Toren Vale" },
  { id: 41, name: "Amber Lens", ratings: "⭐⭐⭐⭐⭐", author: "Fiona Crest" },
  { id: 42, name: "Sapphire Remote", ratings: "⭐⭐⭐", author: "Ellis Thorn" },
  { id: 43, name: "Ruby Speaker", ratings: "⭐⭐⭐⭐", author: "Maeve Ember" },
  { id: 44, name: "Onyx Stand", ratings: "⭐⭐", author: "Jude Frost" },
  {
    id: 45,
    name: "Pearl Projector",
    ratings: "⭐⭐⭐⭐⭐",
    author: "Nia Willow",
  },
  { id: 46, name: "Garnet Hub", ratings: "⭐⭐⭐", author: "Soren Mist" },
  { id: 47, name: "Topaz Cam", ratings: "⭐⭐⭐⭐", author: "Talia Fern" },
  { id: 48, name: "Jade Mouse", ratings: "⭐", author: "Arlo Dune" },
  {
    id: 49,
    name: "Amethyst Board",
    ratings: "⭐⭐⭐⭐⭐",
    author: "Vera Bloom",
  },
  { id: 50, name: "Turquoise Pen", ratings: "⭐⭐⭐", author: "Cillian Shade" },
  { id: 51, name: "Obsidian Dock", ratings: "⭐⭐⭐⭐", author: "Eira Snow" },
  { id: 52, name: "Citrine Lamp", ratings: "⭐⭐", author: "Remy Gale" },
  {
    id: 53,
    name: "Aquamarine Mic",
    ratings: "⭐⭐⭐⭐⭐",
    author: "Sasha Crest",
  },
  { id: 54, name: "Peridot Case", ratings: "⭐⭐⭐", author: "Larkin Vow" },
  {
    id: 55,
    name: "Malachite Drive",
    ratings: "⭐⭐⭐⭐",
    author: "Nova Quill",
  },
  { id: 56, name: "Lapis Charger", ratings: "⭐", author: "Tobin Reed" },
  {
    id: 57,
    name: "Moonstone Key",
    ratings: "⭐⭐⭐⭐⭐",
    author: "Celeste Wren",
  },
  { id: 58, name: "Sunstone Pad", ratings: "⭐⭐⭐", author: "Dorian Blaze" },
  { id: 59, name: "Agate Scanner", ratings: "⭐⭐⭐⭐", author: "Lyric Dawn" },
  { id: 60, name: "Coral Frame", ratings: "⭐⭐", author: "Milo Flint" },
  {
    id: 61,
    name: "Tigerseye Clock",
    ratings: "⭐⭐⭐⭐⭐",
    author: "Anya Vale",
  },
  { id: 62, name: "Hematite Band", ratings: "⭐⭐⭐", author: "Ezra Tide" },
  { id: 63, name: "Fluorite Lens", ratings: "⭐⭐⭐⭐", author: "Tara Bloom" },
  { id: 64, name: "Rosewood Hub", ratings: "⭐", author: "Galen Frost" },
  {
    id: 65,
    name: "Ebony Speaker",
    ratings: "⭐⭐⭐⭐⭐",
    author: "Sigrid Pine",
  },
  { id: 66, name: "Mahogany Stand", ratings: "⭐⭐⭐", author: "Finn Ember" },
  { id: 67, name: "Cedar Router", ratings: "⭐⭐⭐⭐", author: "Liora Cloud" },
  { id: 68, name: "Maple Drive", ratings: "⭐⭐", author: "Cora Slate" },
  { id: 69, name: "Walnut Cam", ratings: "⭐⭐⭐⭐⭐", author: "Elian Ray" },
  { id: 70, name: "Bamboo Mouse", ratings: "⭐⭐⭐", author: "Veda Storm" },
  { id: 71, name: "Teak Board", ratings: "⭐⭐⭐⭐", author: "Jonas Leaf" },
  { id: 72, name: "Pine Pen", ratings: "⭐", author: "Mira Haze" },
  { id: 73, name: "Oak Charger", ratings: "⭐⭐⭐⭐⭐", author: "Tessa Glade" },
  { id: 74, name: "Birch Key", ratings: "⭐⭐⭐", author: "Lyle Crest" },
  { id: 75, name: "Spruce Pad", ratings: "⭐⭐⭐⭐", author: "Fiona Quill" },
  { id: 76, name: "Ash Scanner", ratings: "⭐⭐", author: "Soren Vale" },
  { id: 77, name: "Elm Frame", ratings: "⭐⭐⭐⭐⭐", author: "Nia Thorn" },
  { id: 78, name: "Yew Clock", ratings: "⭐⭐⭐", author: "Rory Ember" },
  { id: 79, name: "Sycamore Band", ratings: "⭐⭐⭐⭐", author: "Lyra Fern" },
  { id: 80, name: "Willow Lens", ratings: "⭐", author: "Caleb Dune" },
  { id: 81, name: "Chestnut Hub", ratings: "⭐⭐⭐⭐⭐", author: "Eira Spark" },
  { id: 82, name: "Alder Speaker", ratings: "⭐⭐⭐", author: "Talia Mist" },
  { id: 83, name: "Hazel Stand", ratings: "⭐⭐⭐⭐", author: "Jude Bloom" },
  { id: 84, name: "Poplar Cam", ratings: "⭐⭐", author: "Vera Snow" },
  { id: 85, name: "Linden Mouse", ratings: "⭐⭐⭐⭐⭐", author: "Sasha Reed" },
  { id: 86, name: "Holly Board", ratings: "⭐⭐⭐", author: "Larkin Vow" },
  { id: 87, name: "Ivy Pen", ratings: "⭐⭐⭐⭐", author: "Nova Crest" },
  { id: 88, name: "Vine Charger", ratings: "⭐", author: "Tobin Wren" },
  { id: 89, name: "Fern Key", ratings: "⭐⭐⭐⭐⭐", author: "Celeste Blaze" },
  { id: 90, name: "Moss Pad", ratings: "⭐⭐⭐", author: "Dorian Quill" },
  { id: 91, name: "Clover Scanner", ratings: "⭐⭐⭐⭐", author: "Lyric Vale" },
  { id: 92, name: "Thistle Frame", ratings: "⭐⭐", author: "Milo Thorn" },
  {
    id: 93,
    name: "Heather Clock",
    ratings: "⭐⭐⭐⭐⭐",
    author: "Anya Ember",
  },
  { id: 94, name: "Laurel Band", ratings: "⭐⭐⭐", author: "Ezra Fern" },
  { id: 95, name: "Sage Lens", ratings: "⭐⭐⭐⭐", author: "Tara Dune" },
  { id: 96, name: "Basil Hub", ratings: "⭐", author: "Galen Spark" },
  {
    id: 97,
    name: "Mint Speaker",
    ratings: "⭐⭐⭐⭐⭐",
    author: "Sigrid Mist",
  },
  { id: 98, name: "Rosemary Stand", ratings: "⭐⭐⭐", author: "Finn Bloom" },
  { id: 99, name: "Thyme Cam", ratings: "⭐⭐⭐⭐", author: "Liora Snow" },
  { id: 100, name: "Parsley Mouse", ratings: "⭐⭐", author: "Cora Reed" },
  {
    id: 101,
    name: "Oregano Board",
    ratings: "⭐⭐⭐⭐⭐",
    author: "Elian Vow",
  },
];
